### ISSUE TITLE
Query Error "FAILED: ParseException line 2:4 cannot recognize input near 'FORMAT' 'SERDE' ''org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'' in column type"

### ISSUE THREAD

**Issue by ravigoku** [secdatabase/SEC-XBRL-Financial-Statement-Dataset#1]
Curious if anyone had a similar exception when copying in pasting the code in sec_financial_statements.company_submission.sql in athena engine version 1 & version 2:

"FAILED: ParseException line 2:4 cannot recognize input near 'FORMAT' 'SERDE' ''org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'' in column type"

It may be a syntax error, but I wasn't able to figure it out...
![image](https://user-images.githubusercontent.com/11988081/115126246-7dcbb880-9f82-11eb-98a8-4a7acd81d203.png)

**Comment by ravigoku** [comment]
![image](https://user-images.githubusercontent.com/11988081/115126259-8a501100-9f82-11eb-909b-d5227b5d184d.png)

**Comment by secdatabase** [comment]
It is the Athena Web Interface does not support the comments. Removing the link after '--' will fix it.

**Comment by secdatabase** [comment]
This is resolved by removing the comments
